[package]
name = "start"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4.3"
proconio = "0.4.3"
itertools = "0.11.0"
rand = "0.8.5"
permutohedron = "0.2.4"